# Generated by Django 5.2.8 on 2025-11-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="created_by",
            new_name="user",
        ),
    ]
