# Generated by Django 5.2.8 on 2025-11-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_rename_created_by_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
